# --> check the technical writing for various characteristics
- writing/reflection.md:
  - description: Ensure that reflection.md file exists in the writing/ directory
    check: ConfirmFileExists
  # - description: Write a minimum number of meaningful words (adding around 100 words in total) in the reflection
  #   check: CountFileWords
  #   options:
  #     count: 500
  #     exact: false
  - description: Complete all TODOs, remove the TODO markers in the reflection.md
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the reflection file
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true

# --> check the code for various characteristics
- ./main.py:
  - description: Ensure that ./main.py file exists
    check: ConfirmFileExists
  - description: Complete all TODOs, remove the TODO markers in the File ./main.py
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the File ./main.py
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true


# --> check the code for various characteristics
- ./main_spaghetti_code.py:
  - description: Ensure that ./main_spaghetti_code.py file exists
    check: ConfirmFileExists
  # - description: Complete all TODOs, remove the TODO markers in the File ./main_spaghetti_code.py
  #   check: MatchFileFragment
  #   options:
  #     fragment: TODO
  #     count: 0
  #     exact: true
  # - description: Delete the 'Add Your Name Here' prompt in the File ./main_spaghetti_code.py
  #   check: MatchFileFragment
  #   options:
  #     fragment: "Add Your Name Here"
  #     count: 0
  #     exact: true

# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (5) in repository
  check: CountCommits
  options:
    count: 5